typography_spectrum: 0.911054520867765
color:
  brandStrength: 0.18173278286121786
  lightness: 0.8818144500255585
  saturation: 0.001711441669613123
  rhythmicContrast: 0.05560101568698883
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
layout_spectrum: 0.7145433283876628
analytics:
  google: UA-20895326-1
author:
  name: Mike Horwath
  email: geekandi@geeks.org
  url: 'https://www.geekandi.com/'
name: Geek and I
navigation:
  - name: About
    url: 'https://www.geekandi.com/about/'
    type: external
title: feed; an embellishment
description: Everything you never wanted to read about
